#if 0
//
// Generated by 2.0.21119.0
//
//   fxc /T ps_2_0 /Fh headers/d3dx/ps_2_0.h /Vn g_ps_2_0 pixel_shader.hlsl
//
//
// Parameters:
//
//   sampler2D LinearSampler;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   LinearSampler s0       1
//

// Shader type: pixel 

xps_3_0
defconst LinearSampler, sampler2d, object, [1, 1], s0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=2
// PsExportColorCount=1
// PsSampleControl=centers

dcl_texcoord r0
dcl_texcoord1 r1.xy
dcl_texcoord2 r2.xy


    exec
    tfetch2D r2, r2.xy, tf0
    tfetch2D r1, r1.xy, tf0
    alloc colors
    exece
    mul r0, r1, r0
    mul oC0, r0, r2

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_ps_2_0[] =
{
    0x102a1100, 0x000000b8, 0x00000054, 0x00000000, 0x00000024, 0x00000000, 
    0x0000008c, 0x00000000, 0x00000000, 0x00000064, 0x0000001c, 0x00000057, 
    0xffff0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000050, 0x00000030, 
    0x00030000, 0x00010000, 0x00000040, 0x00000000, 0x4c696e65, 0x61725361, 
    0x6d706c65, 0x7200abab, 0x0004000c, 0x00010001, 0x00010000, 0x00000000, 
    0x70735f33, 0x5f300032, 0x2e302e32, 0x31313139, 0x2e3000ab, 0x00000000, 
    0x00000054, 0x10000200, 0x00000004, 0x00000000, 0x00002063, 0x00070007, 
    0x00000001, 0x0000f050, 0x00003151, 0x00003252, 0x00052002, 0x00001200, 
    0xc4000000, 0x00002004, 0x00002200, 0x00000000, 0x10082041, 0x1f1ff688, 
    0x00004000, 0x10081021, 0x1f1ff688, 0x00004000, 0xc80f0000, 0x00000000, 
    0xe1010000, 0xc80f8000, 0x00000000, 0xe1000200, 0x00000000, 0x00000000, 
    0x00000000
};
